name: sensor.personalcapital
description: 💵 Personal Capital component for Home Assistant
type: component
keywords:
  - sensor
  - personalcapital
  - finance
  - money
  - accounts
author:
  name: Jonny Tran
  email: jonny@extralit.io
  homepage: https://jonnytran.github.io
license: MIT
files:
  - custom_components/personalcapital/sensor.py
